import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	docs: [
		{
			type: "category",
			label: "Getting Started",
			collapsed: false,
			link: {
				type: "doc",
				id: "getting-started/index",
			},
			items: ["getting-started/index", "getting-started/about-game-scripts"],
		},
		{
			type: "html",
			value: "<hr/>",
			className: "sidebar-divider",
		},
		{
			type: "category",
			label: "Game Scripts",
			collapsed: false,
			link: {
				type: "generated-index",
				title: "Game Scripts",
				description: "DST game scripts API documentation",
			},
			items: [
				{
					type: "category",
					label: "Prefabs",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Prefabs",
						description: "DST prefabs API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/prefabs", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "category",
					label: "Components",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Components",
						description: "DST components API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/components", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "category",
					label: "Behaviours",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Behaviours",
						description: "DST behaviours API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/behaviours", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "category",
					label: "Brains",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Brains",
						description: "DST brains API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/brains", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "category",
					label: "Cameras",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Cameras",
						description: "DST cameras API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/cameras", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "category",
					label: "Widgets",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Widgets",
						description: "DST widgets API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/widgets",
						},
					],
				},
				{
					type: "category",
					label: "Util",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Util",
						description: "DST util API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/util",
						},
					],
				},
				{
					type: "category",
					label: "Tools",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Tools",
						description: "DST tools API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/tools",
						},
					],
				},
				{
					type: "category",
					label: "Scenarios",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Scenarios",
						description: "DST scenarios API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/scenarios",
						},
					],
				},
				{
					type: "category",
					label: "Map",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Map",
						description: "DST map API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/map",
						},
					],
				},
				{
					type: "category",
					label: "Languages",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "Languages",
						description: "DST languages API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/languages", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "category",
					label: "NIS",
					collapsed: true,
					link: {
						type: "generated-index",
						title: "NIS",
						description: "DST NIS API documentation",
					},
					items: [
						{
							type: "autogenerated",
							dirName: "game-scripts/nis", // từ thư mục `docs/`
						},
					],
				},
				{
					type: "autogenerated",
					dirName: "game-scripts", // từ thư mục `docs/`
				},
			],
		},
		
	],
};

export default sidebars;
